{
  description = "Sideyard: let an AI agent drive your Hyprland (Nixarchy) desktop, with a kill switch";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      inherit (pkgs) lib;
      version = "2.0.0";

      aw-input = pkgs.stdenv.mkDerivation {
        pname = "aw-input";
        inherit version;
        src = ./src/aw_input;
        nativeBuildInputs = with pkgs; [ pkg-config wayland-scanner ];
        buildInputs = with pkgs; [ wayland libxkbcommon ];
        makeFlags = [
          "BUILD=build"
          "WLR_PROTO=${pkgs.wlr-protocols}/share/wlr-protocols/unstable/wlr-virtual-pointer-unstable-v1.xml"
        ];
        installPhase = "install -Dm755 build/aw-input $out/bin/aw-input";
      };

      python = pkgs.python3.withPackages (p: [ p.pygobject3 ]);

      sideyard = pkgs.stdenv.mkDerivation {
        pname = "sideyard";
        inherit version;
        src = ./src;
        nativeBuildInputs = [ pkgs.makeWrapper ];
        installPhase = ''
          mkdir -p $out/lib $out/bin
          cp -r sideyard $out/lib/
          # hyprctl is deliberately not bundled: it must match the running compositor.
          makeWrapper ${python}/bin/python3 $out/bin/sideyard \
            --add-flags "-m sideyard" \
            --set PYTHONPATH $out/lib \
            --set SIDEYARD_HELPER ${aw-input}/bin/aw-input \
            --prefix GI_TYPELIB_PATH : ${lib.makeSearchPath "lib/girepository-1.0" [ pkgs.at-spi2-core pkgs.glib.out pkgs.gobject-introspection ]} \
            --suffix PATH : ${lib.makeBinPath (with pkgs; [ grim wl-clipboard systemd ])}
        '';
        meta.mainProgram = "sideyard";
      };

      # A plain directory (no symlinks inside) so omarchy-plugin-validate accepts it.
      plugin = pkgs.runCommand "sideyard-plugin-${version}" { } ''
        cp -r ${./plugin} $out
        chmod -R u+w $out
        substituteInPlace $out/Command.qml --replace-fail "@sideyard@" "${sideyard}/bin/sideyard"
      '';
    in
    {
      packages.${system} = { inherit aw-input sideyard plugin; default = sideyard; };

      homeManagerModules.default = { config, options, ... }:
        let cfg = config.programs.sideyard;
        in {
          options.programs.sideyard = {
            enable = lib.mkEnableOption "Sideyard agent desktop control";
            killSwitch = lib.mkOption {
              type = lib.types.str;
              default = "SUPER + SHIFT + ESCAPE";
              description = "Hyprland key combo that revokes agent control and releases held keys.";
            };
            a11y.enable = lib.mkOption {
              type = lib.types.bool;
              default = true;
              description = "Expose GTK/Qt accessibility so agents can use a11y_tree/a11y_find/a11y_act.";
            };
          };

          config = lib.mkIf cfg.enable (lib.mkMerge [
            {
              home.packages = [ sideyard ];
              # Load from ~/.config/hypr/bindings.lua with: pcall(require, "hypr.sideyard-binds")
              xdg.configFile."hypr/sideyard-binds.lua".text = ''
                -- Generated by programs.sideyard; edits are overwritten on rebuild.
                o.bind("${cfg.killSwitch}", "Sideyard: stop agent control", "${sideyard}/bin/sideyard control off")
              '';
            }
            (lib.mkIf cfg.a11y.enable {
              home.sessionVariables = {
                QT_LINUX_ACCESSIBILITY_ALWAYS_ON = "1";
                GTK_MODULES = "gail:atk-bridge";
                NO_AT_BRIDGE = "0";
              };
              dconf.settings."org/gnome/desktop/interface".toolkit-accessibility = true;
            })
            (if options ? programs.nixarchy.plugins
            then { programs.nixarchy.plugins.sideyard.src = plugin; }
            else { xdg.configFile."omarchy/plugins/hoppcx.sideyard".source = plugin; })
          ]);
        };

      checks.${system} = {
        unittest = pkgs.runCommand "sideyard-unittest" { nativeBuildInputs = [ python ]; } ''
          cp -r ${./.} src && chmod -R u+w src && cd src
          patchShebangs bin
          XDG_RUNTIME_DIR=$TMPDIR python3 -m unittest discover -s tests -v
          touch $out
        '';
        # Mirrors the checks Nixarchy runs when it installs a plugin.
        plugin = pkgs.runCommand "sideyard-plugin-check" { nativeBuildInputs = [ pkgs.jq ]; } ''
          m=${plugin}/manifest.json
          jq -e '.schemaVersion == 1 and (.id | test("^[A-Za-z0-9][A-Za-z0-9._-]*$")) and .name and .version
                 and (.kinds | index("bar-widget")) and .entryPoints.barWidget
                 and (.barWidget.defaultSection | IN("left", "center", "right"))' $m
          test -f ${plugin}/$(jq -r .entryPoints.barWidget $m)
          test -z "$(find ${plugin} -type l)"
          ! grep -rEw 'pacman|yay' ${plugin}
          ! grep -r '@sideyard@' ${plugin}
          touch $out
        '';
      };

      devShells.${system}.default = pkgs.mkShell {
        packages = with pkgs; [ python pkg-config wayland-scanner wayland libxkbcommon wlr-protocols jq grim wl-clipboard ];
        WLR_PROTO = "${pkgs.wlr-protocols}/share/wlr-protocols/unstable/wlr-virtual-pointer-unstable-v1.xml";
        GI_TYPELIB_PATH = lib.makeSearchPath "lib/girepository-1.0" [ pkgs.at-spi2-core pkgs.glib.out pkgs.gobject-introspection ];
      };
    };
}
